dashboard:
  url:
  label: Dashboard
  icon: fa fa-dashboard
games:
  label: Games
  icon: fa fa-id-card
  children:
    list:
      label: Game List
      url: game/list
    new:
      label: New Game
      url: game/new
players:
  label: Players
  icon: fa fa-user
  children:
    list:
      label: Player List
      url: player/list
    edit:
      label: New Player
      url: player/edit
wonders:
  label: Wonders
  icon: glyphicon glyphicon-triangle-top
  children:
    list:
      label: Wonder List
      url: wonder/list
    edit:
      label: New Wonder
      url: wonder/edit
categories:
  label: Score Categories
  icon: fa fa-superpowers
  children:
    list:
      label: Score Category List
      url: category/list
    edit:
      label: New Score Category
      url: category/edit
reports:
  label: Reports
  icon: fa fa-table
  children:
    wonder:
      label: Wonder Reports
      url: report/wonder
    category:
      label: Score Category Reports
      url: report/category



