home:
  controller: \Controller\IndexController
  method: get
  bind: /
#PLAYERS
player_list:
  controller: \Controller\Player\ListPlayer
  pageTitle: Players list
  selectedMenu:
    - players
    - players-list
  template: default.html.twig
  method: get
  bind: player/list
player_new:
  controller: \Controller\Player\EditPlayer
  method: get
  template: player/edit.html.twig
  selectedMenu:
    - players
    - players-new
  bind: player/new
player_edit:
  controller: \Controller\Player\EditPlayer
  method: get
  template: player/edit.html.twig
  selectedMenu:
    - players
  bind: player/edit
player_save:
  controller: \Controller\Player\SavePlayer
  method: post
  bind: player/save

#SCORE CATEGORIES
category_list:
  controller: \Controller\Category\ListCategory
  pageTitle: Score Categories list
  selectedMenu:
    - categories
    - categories-list
  template: default.html.twig
  method: get
  bind: category/list

category_new:
  controller: \Controller\Category\EditCategory
  method: get
  template: category/edit.html.twig
  selectedMenu:
    - categories
    - categories-new
  bind: category/new
category_edit:
  controller: \Controller\Category\EditCategory
  method: get
  template: category/edit.html.twig
  selectedMenu:
    - categories
  bind: category/edit
category_save:
  controller: \Controller\Category\SaveCategory
  method: post
  redirect: /category/list
  bind: category/save

# WONDERS
wonder_list:
  controller: \Controller\Wonder\ListWonder
  method: get
  pageTitle: Wonder list
  selectedMenu:
    - wonders
    - wonders-list
  template: default.html.twig
  page_title: Wonders List
  bind: wonder/list
wonder_new:
  controller: \Controller\Wonder\EditWonder
  method: get
  template: wonder/edit.html.twig
  selectedMenu:
    - wonders
    - wonders-new
  bind: wonder/new
wonder_edit:
  controller: \Controller\Wonder\EditWonder
  template: wonder/edit.html.twig
  selectedMenu:
    - wonders
  method: get
  bind: wonder/edit
wonder_save:
  controller: \Controller\Wonder\SaveWonder
  method: post
  bind: wonder/save

wonder_group_list:
  controller: \Controller\WonderGroup\ListWonderGroup
  method: get
  pageTitle: Wonder Group list
  selectedMenu:
    - wonders
    - wonders-group-list
  template: default.html.twig
  bind: wonder-group/list
wonder_group_new:
  controller: \Controller\WonderGroup\EditWonderGroup
  method: get
  template: wonder-group/edit.html.twig
  selectedMenu:
    - wonders
    - wonders-group-new
  bind: wonder-group/new
wonder_group_edit:
  controller: \Controller\WonderGroup\EditWonderGroup
  template: wonder-group/edit.html.twig
  selectedMenu:
    - wonders
  method: get
  bind: wonder-group/edit
wonder_group_save:
  controller: \Controller\WonderGroup\SaveWonderGroup
  method: post
  bind: wonder-group/save

# GAME
game_list:
  controller: \Controller\Game\ListGame
  method: get
  pageTitle: Games list
  selectedMenu:
    - games
    - games-list
  template: default.html.twig
  bind: game/list
game_view:
  controller: \Controller\Game\ViewGame
  method: get
  template: default.html.twig
  pageTitle: View Game Scores
  selectedMenu:
    - games
  bind: game/view
game_new:
  controller: \Controller\Game\NewGame
  template: game/new.html.twig
  selectedMenu:
    - games
    - games-new
  method: get
  pageTitle: Add new game score
  bind: game/new
game_save:
  controller: \Controller\Game\SaveGame
  method: post
  redirect: /game/list
  bind: game/save
login:
  controller: \Controller\Login\Index
  template: login/index.html.twig
  pageTitle: Login
  method: get
  bind: login
login_post:
  controller: \Controller\Login\Post
  method: post
  bind: login/post
logout:
  controller: \Controller\Login\Logout
  method: get
  bind: logout

#REPORTS
report_wonder:
  controller: \Controller\Report\Stats\Wonder
  template: report.html.twig
  selectedMenu:
    - reports
    - reports-wonder
  method: get
  pageTitle: Wonder stats
  bind: report/wonder
report_category:
  controller: \Controller\Report\Stats\Category
  method: get
  template: report.html.twig
  selectedMenu:
    - reports
    - reports-category
  pageTitle: Category stats
  bind: report/category
heartbeat:
  controller: \Controller\Heartbeat
  method: get
  bind: heartbeat
