home:
  controller: \Controller\IndexController
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Dashboard
  bind: /
#PLAYERS
player_list:
  controller: \Controller\Player\ListPlayer
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Players List
  bind: player/list
player_new:
  controller: \Controller\Player\EditPlayer
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Add new player
  bind: player/new
player_edit:
  controller: \Controller\Player\EditPlayer
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Edit Player
  bind: player/edit
player_save:
  controller: \Controller\Player\SavePlayer
  dependencies:
    - request
    - session
  method: post
  bind: player/save

#SCORE CATEGORIES
category_list:
  controller: \Controller\Category\ListCategory
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Score categories list
  bind: category/list

category_new:
  controller: \Controller\Category\EditCategory
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Add new score category
  bind: category/new
category_edit:
  controller: \Controller\Category\EditCategory
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Edit score category
  bind: category/edit
category_save:
  controller: \Controller\Category\SaveCategory
  dependencies:
    - request
    - session
  method: post
  redirect: /category/list
  bind: category/save
# WONDERS
wonder_list:
  controller: \Controller\Wonder\ListWonder
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Wonders List
  bind: wonder/list
wonder_new:
  controller: \Controller\Wonder\EditWonder
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Add new Wonder
  bind: wonder/new
wonder_edit:
  controller: \Controller\Wonder\EditWonder
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Edit Wonder
  bind: wonder/edit
wonder_save:
  controller: \Controller\Wonder\SaveWonder
  dependencies:
    - request
    - session
  method: post
  bind: wonder/save

# GAME
game_list:
  controller: \Controller\Game\ListGame
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Games list
  bind: game/list
game_view:
  controller: \Controller\Game\ViewGame
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: View Game Scores
  bind: game/view
game_new:
  controller: \Controller\Game\NewGame
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Add new game score
  bind: game/new
game_save:
  controller: \Controller\Game\SaveGame
  dependencies:
    - request
    - session
  method: post
  redirect: /game/list
  bind: game/save
login:
  controller: \Controller\Login\Index
  template: login/index.html.twig
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  bind: login
login_post:
  controller: \Controller\Login\Post
  dependencies:
    - request
    - session
    - hash
  method: post
  bind: login/post
logout:
  controller: \Controller\Login\Logout
  dependencies:
    - request
    - session
  method: get
  bind: logout

#REPORTS
report_wonder:
  controller: \Controller\Report\Stats\Wonder
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Wonder stats
  bind: report/wonder
report_category:
  controller: \Controller\Report\Stats\Category
  dependencies:
    - request
    - session
    - menuBuilder
    - twig
  method: get
  page_title: Category stats
  bind: report/category
heartbeat:
  controller: \Controller\HeartbeatController
  dependencies:
    - request
    - session
  method: get
  bind: heartbeat
